### ISSUE TITLE
Any plan for for Murch seed read support?

### ISSUE THREAD

**Issue by NotYuzuki** [LegoFigure11/Splat3GearView#6]
From the future plan, it seems there is a plan for Gacha, so I would wonder whether the similar four seed-based Murch support would be also taken into the consideration :)

**Comment by LegoFigure11** [comment]
If you can find them in RAM I'd b more than happy to add it!

It seems like the other seeds are stored in a save block that's shuffled, at least that's what I found when researching how the gacha seeds are stored. If someone finds how this block is being shuffled or the keys I can search for to identify the values, adding this will be a lot more feasible. I'll continue to look in to it myself but likely won't be able to dedicate much time to it for a good while.
