### ISSUE TITLE
Immediately disconnected from switch

### ISSUE THREAD

**Issue by WisteriaSp** [LegoFigure11/Splat3GearView#7]
Program connects to my switch and then immediately disconnects from it. Unable to view my gear due to this issue.

Using:
sys-botbase's latest release
Switch running on 15.0.1, AMS 1.4.0
Build from https://github.com/LegoFigure11/Splat3GearView/issues/4

Log:
[SysBotLog.txt](https://github.com/LegoFigure11/Splat3GearView/files/10398153/SysBotLog.txt)

**Comment by LegoFigure11** [comment]
Can you try on the latest dev build? https://nightly.link/LegoFigure11/Splat3GearView/workflows/dotnet-desktop/main/Splat3GearView.zip

Sounds like it might be trying to read from the wrong offsets.

**Comment by WisteriaSp** [comment]
Tried it and I'm ending up with the same issue. Something I'd like to note is that Shiverbot is able to connect to my switch, so I'm not really sure what would be causing this

![image](https://user-images.githubusercontent.com/117503600/211975674-a2e8cb8a-66f0-4cea-9b4d-ecec27e7da65.png)

**Comment by LegoFigure11** [comment]
Most likely an offset issue, I'll look in to it after work.  Thanks for bring this to my attention!

**Comment by WisteriaSp** [comment]
No problem! Thanks for the help

**Comment by LegoFigure11** [comment]
Are you able to double check that you're on the latest version of Splatoon 3 (2.0.1)? Also you've said that ShiverBot can connect fine, are you able to send me a zip of shiverbot's `addresses` folder? I can't get ShiverBot to connect to my switch on the latest splatoon version because of invalid addresses, which makes me think maybe there's a version mismatch happening somewhere here.

**Comment by WisteriaSp** [comment]
Yes, here's the zip. 
[addresses.zip](https://github.com/LegoFigure11/Splat3GearView/files/10398322/addresses.zip) I've downloaded address .txt files that allow Shiverbot to connect to the newer versions. Gear seed checking doesn't seem to work, but the plaza printer does. Main reason why I brought it up was due to the fact that it also uses sys-botbase

**Comment by WisteriaSp** [comment]
Also here's my pic of S3 on v2.0.1
![image](https://user-images.githubusercontent.com/117503600/211981364-0e798515-9928-4cd8-a9df-376b81fcb8d5.png)

**Comment by LegoFigure11** [comment]
Thanks!

What's likely happening is that it is actually connecting, but tries (and fails, for some reason) to read the data, then disconnects. If it doesn't actually throw any errors and just immediately jumps to "disconnected" in the status. this is most likely the case (meaning it's not a connection issue).

Out of curiosity, are you running any other cheats/mods/overlays/other sysmodules/anything else that might shift RAM at all (edizon, tesla, or anything that connects to dmnt::cht are likely culprits). Booting the game holding L may magically make things start working again.

**Comment by WisteriaSp** [comment]
Hmm, yeah when I connect it quickly cycles through "Reading Headgear/Clothes/Shoes" and then jumps to disconnect. I am actually running Tesla menu and apparently a version of Edizon that crashes my system if I open it lmao. I'll try disabling a few of these things and seeing if that fixes it. Also disabling mods by holding L didn't seem to work
![image](https://user-images.githubusercontent.com/117503600/211984152-874ee1e6-3711-4781-bc36-aa8165b788dc.png)
![image](https://user-images.githubusercontent.com/117503600/211984255-fefe1ca0-2d0a-4866-80c2-f76409f31bd8.png)

**Comment by WisteriaSp** [comment]
Disabling my sysmodules fixed it, thanks for the help!

**Comment by LegoFigure11** [comment]
Sweet, glad you got it working!
