### ISSUE TITLE
Version 2.1.0 Support

### ISSUE THREAD

**Issue by NotYuzuki** [LegoFigure11/Splat3GearView#8]
Is there a recent update drop plan for supporting version 2.1.0? Or could you help share some tricks/hints for finding new offsets w/ sysbot module?

**Comment by LegoFigure11** [comment]
I plan on updating the offsets for 2.1.0 after work today

**Comment by LegoFigure11** [comment]
Closed by d985820

Grab the latest commit build from the link in the readme once it's finished building
